"""Generated from runtime metadata by codegen. DO NOT EDIT BY HAND.

Regenerate with: python -m codegen <ws-endpoint>
Spec version: 441
"""
from dataclasses import dataclass

@dataclass(frozen=True)
class ErrorInfo:
    pallet: str
    name: str
    docs: str


ERRORS: dict[tuple[int, int], ErrorInfo] = {
    (0, 0): ErrorInfo('System', 'InvalidSpecName', 'The name of specification does not match between the current runtime and the new runtime.'),
    (0, 1): ErrorInfo('System', 'SpecVersionNeedsToIncrease', 'The specification version is not allowed to decrease between the current runtime and the new runtime.'),
    (0, 2): ErrorInfo('System', 'FailedToExtractRuntimeVersion', 'Failed to extract the runtime version from the new runtime.  Either calling `Core_version` or decoding `RuntimeVersion` failed.'),
    (0, 3): ErrorInfo('System', 'NonDefaultComposite', 'Suicide called when the account has non-default composite data.'),
    (0, 4): ErrorInfo('System', 'NonZeroRefCount', 'There is a non-zero reference count preventing the account from being purged.'),
    (0, 5): ErrorInfo('System', 'CallFiltered', 'The origin filter prevent the call to be dispatched.'),
    (0, 6): ErrorInfo('System', 'MultiBlockMigrationsOngoing', 'A multi-block migration is ongoing and prevents the current code from being replaced.'),
    (0, 7): ErrorInfo('System', 'NothingAuthorized', 'No upgrade authorized.'),
    (0, 8): ErrorInfo('System', 'Unauthorized', 'The submitted code is not authorized.'),
    (4, 0): ErrorInfo('Grandpa', 'PauseFailed', "Attempt to signal GRANDPA pause when the authority set isn't live (either paused or already pending pause)."),
    (4, 1): ErrorInfo('Grandpa', 'ResumeFailed', "Attempt to signal GRANDPA resume when the authority set isn't paused (either live or already pending resume)."),
    (4, 2): ErrorInfo('Grandpa', 'ChangePending', 'Attempt to signal GRANDPA change with one already pending.'),
    (4, 3): ErrorInfo('Grandpa', 'TooSoon', 'Cannot signal forced change so soon after last.'),
    (4, 4): ErrorInfo('Grandpa', 'InvalidKeyOwnershipProof', 'A key ownership proof provided as part of an equivocation report is invalid.'),
    (4, 5): ErrorInfo('Grandpa', 'InvalidEquivocationProof', 'An equivocation proof provided as part of an equivocation report is invalid.'),
    (4, 6): ErrorInfo('Grandpa', 'DuplicateOffenceReport', 'A given equivocation report is valid but already previously reported.'),
    (5, 0): ErrorInfo('Balances', 'VestingBalance', 'Vesting balance too high to send value.'),
    (5, 1): ErrorInfo('Balances', 'LiquidityRestrictions', 'Account liquidity restrictions prevent withdrawal.'),
    (5, 2): ErrorInfo('Balances', 'InsufficientBalance', 'Balance too low to send value.'),
    (5, 3): ErrorInfo('Balances', 'ExistentialDeposit', 'Value too low to create account due to existential deposit.'),
    (5, 4): ErrorInfo('Balances', 'Expendability', 'Transfer/payment would kill account.'),
    (5, 5): ErrorInfo('Balances', 'ExistingVestingSchedule', 'A vesting schedule already exists for this account.'),
    (5, 6): ErrorInfo('Balances', 'DeadAccount', 'Beneficiary account must pre-exist.'),
    (5, 7): ErrorInfo('Balances', 'TooManyReserves', 'Number of named reserves exceed `MaxReserves`.'),
    (5, 8): ErrorInfo('Balances', 'TooManyHolds', 'Number of holds exceed `VariantCountOf<T::RuntimeHoldReason>`.'),
    (5, 9): ErrorInfo('Balances', 'TooManyFreezes', 'Number of freezes exceed `MaxFreezes`.'),
    (5, 10): ErrorInfo('Balances', 'IssuanceDeactivated', 'The issuance cannot be modified since it is already deactivated.'),
    (5, 11): ErrorInfo('Balances', 'DeltaZero', 'The delta cannot be zero.'),
    (7, 0): ErrorInfo('SubtensorModule', 'RootNetworkDoesNotExist', 'The root network does not exist.'),
    (7, 1): ErrorInfo('SubtensorModule', 'InvalidIpType', 'The user is trying to serve an axon which is not of type 4 (IPv4) or 6 (IPv6).'),
    (7, 2): ErrorInfo('SubtensorModule', 'InvalidIpAddress', 'An invalid IP address is passed to the serve function.'),
    (7, 3): ErrorInfo('SubtensorModule', 'InvalidPort', 'An invalid port is passed to the serve function.'),
    (7, 4): ErrorInfo('SubtensorModule', 'HotKeyNotRegisteredInSubNet', 'The hotkey is not registered in subnet'),
    (7, 5): ErrorInfo('SubtensorModule', 'HotKeyAccountNotExists', 'The hotkey does not exists'),
    (7, 6): ErrorInfo('SubtensorModule', 'HotKeyNotRegisteredInNetwork', 'The hotkey is not registered in any subnet.'),
    (7, 7): ErrorInfo('SubtensorModule', 'NonAssociatedColdKey', 'Request to stake, unstake or subscribe is made by a coldkey that is not associated with the hotkey account.'),
    (7, 8): ErrorInfo('SubtensorModule', 'NotEnoughStake', 'The caller does not have enought stake to perform this action.'),
    (7, 9): ErrorInfo('SubtensorModule', 'NotEnoughStakeToWithdraw', 'The caller is requesting removing more stake than there exists in the staking account. See: "[remove_stake()]".'),
    (7, 10): ErrorInfo('SubtensorModule', 'NotEnoughStakeToSetWeights', 'The caller is requesting to set weights but the caller has less than minimum stake required to set weights (less than WeightsMinStake).'),
    (7, 11): ErrorInfo('SubtensorModule', 'NotEnoughStakeToSetChildkeys', "The parent hotkey doesn't have enough own stake to set childkeys."),
    (7, 12): ErrorInfo('SubtensorModule', 'NotEnoughBalanceToStake', 'The caller is requesting adding more stake than there exists in the coldkey account. See: "[add_stake()]"'),
    (7, 13): ErrorInfo('SubtensorModule', 'BalanceWithdrawalError', 'The caller is trying to add stake, but for some reason the requested amount could not be withdrawn from the coldkey account.'),
    (7, 14): ErrorInfo('SubtensorModule', 'ZeroBalanceAfterWithdrawn', 'Unsuccessfully withdraw, balance could be zero (can not make account exist) after withdrawal.'),
    (7, 15): ErrorInfo('SubtensorModule', 'NeuronNoValidatorPermit', 'The caller is attempting to set non-self weights without being a permitted validator.'),
    (7, 16): ErrorInfo('SubtensorModule', 'WeightVecNotEqualSize', 'The caller is attempting to set the weight keys and values but these vectors have different size.'),
    (7, 17): ErrorInfo('SubtensorModule', 'DuplicateUids', 'The caller is attempting to set weights with duplicate UIDs in the weight matrix.'),
    (7, 18): ErrorInfo('SubtensorModule', 'UidVecContainInvalidOne', 'The caller is attempting to set weight to at least one UID that does not exist in the metagraph.'),
    (7, 19): ErrorInfo('SubtensorModule', 'WeightVecLengthIsLow', 'The dispatch is attempting to set weights on chain with fewer elements than are allowed.'),
    (7, 20): ErrorInfo('SubtensorModule', 'TooManyRegistrationsThisBlock', 'Number of registrations in this block exceeds the allowed number (i.e., exceeds the subnet hyperparameter "max_regs_per_block").'),
    (7, 21): ErrorInfo('SubtensorModule', 'HotKeyAlreadyRegisteredInSubNet', 'The caller is requesting registering a neuron which already exists in the active set.'),
    (7, 22): ErrorInfo('SubtensorModule', 'NewHotKeyIsSameWithOld', 'The new hotkey is the same as old one'),
    (7, 23): ErrorInfo('SubtensorModule', 'NewHotKeyNotCleanForRootSwap', 'The new hotkey has outstanding root claimable or non-zero root stake, so the root rate-book cannot be merged without misallocating dividends.'),
    (7, 24): ErrorInfo('SubtensorModule', 'InvalidWorkBlock', 'The supplied PoW hash block is in the future or negative.'),
    (7, 25): ErrorInfo('SubtensorModule', 'InvalidDifficulty', 'The supplied PoW hash block does not meet the network difficulty.'),
    (7, 26): ErrorInfo('SubtensorModule', 'InvalidSeal', 'The supplied PoW hash seal does not match the supplied work.'),
    (7, 27): ErrorInfo('SubtensorModule', 'MaxWeightExceeded', 'The dispatch is attempting to set weights on chain with weight value exceeding the configured max weight limit (currently `u16::MAX`).'),
    (7, 28): ErrorInfo('SubtensorModule', 'HotKeyAlreadyDelegate', 'The hotkey is attempting to become a delegate when the hotkey is already a delegate.'),
    (7, 29): ErrorInfo('SubtensorModule', 'SettingWeightsTooFast', 'A transactor exceeded the rate limit for setting weights.'),
    (7, 30): ErrorInfo('SubtensorModule', 'IncorrectWeightVersionKey', 'A validator is attempting to set weights from a validator with incorrect weight version.'),
    (7, 31): ErrorInfo('SubtensorModule', 'ServingRateLimitExceeded', 'An axon or prometheus serving exceeded the rate limit for a registered neuron.'),
    (7, 32): ErrorInfo('SubtensorModule', 'UidsLengthExceedUidsInSubNet', 'The caller is attempting to set weights with more UIDs than allowed.'),
    (7, 33): ErrorInfo('SubtensorModule', 'NetworkTxRateLimitExceeded', 'A transactor exceeded the rate limit for add network transaction.'),
    (7, 34): ErrorInfo('SubtensorModule', 'DelegateTxRateLimitExceeded', 'A transactor exceeded the rate limit for delegate transaction.'),
    (7, 35): ErrorInfo('SubtensorModule', 'HotKeySetTxRateLimitExceeded', 'A transactor exceeded the rate limit for setting or swapping hotkey.'),
    (7, 36): ErrorInfo('SubtensorModule', 'StakingRateLimitExceeded', 'A transactor exceeded the rate limit for staking.'),
    (7, 37): ErrorInfo('SubtensorModule', 'SubNetRegistrationDisabled', 'Registration is disabled.'),
    (7, 38): ErrorInfo('SubtensorModule', 'TooManyRegistrationsThisInterval', 'The number of registration attempts exceeded the allowed number in the interval.'),
    (7, 39): ErrorInfo('SubtensorModule', 'TransactorAccountShouldBeHotKey', 'The hotkey is required to be the origin.'),
    (7, 40): ErrorInfo('SubtensorModule', 'FaucetDisabled', 'Faucet is disabled.'),
    (7, 41): ErrorInfo('SubtensorModule', 'NotSubnetOwner', 'Not a subnet owner.'),
    (7, 42): ErrorInfo('SubtensorModule', 'RegistrationNotPermittedOnRootSubnet', 'Operation is not permitted on the root subnet.'),
    (7, 43): ErrorInfo('SubtensorModule', 'StakeTooLowForRoot', 'A hotkey with too little stake is attempting to join the root subnet.'),
    (7, 44): ErrorInfo('SubtensorModule', 'AllNetworksInImmunity', 'All subnets are in the immunity period.'),
    (7, 45): ErrorInfo('SubtensorModule', 'NotEnoughBalanceToPaySwapHotKey', 'Not enough balance to pay swapping hotkey.'),
    (7, 46): ErrorInfo('SubtensorModule', 'NotRootSubnet', 'Netuid does not match for setting root network weights.'),
    (7, 47): ErrorInfo('SubtensorModule', 'CanNotSetRootNetworkWeights', 'Can not set weights for the root network.'),
    (7, 48): ErrorInfo('SubtensorModule', 'NoNeuronIdAvailable', 'No neuron ID is available.'),
    (7, 49): ErrorInfo('SubtensorModule', 'DelegateTakeTooLow', 'Delegate take is too low.'),
    (7, 50): ErrorInfo('SubtensorModule', 'DelegateTakeTooHigh', 'Delegate take is too high.'),
    (7, 51): ErrorInfo('SubtensorModule', 'NoWeightsCommitFound', 'No commit found for the provided hotkey+netuid combination when attempting to reveal the weights.'),
    (7, 52): ErrorInfo('SubtensorModule', 'InvalidRevealCommitHashNotMatch', 'Committed hash does not equal the hashed reveal data.'),
    (7, 53): ErrorInfo('SubtensorModule', 'CommitRevealEnabled', 'Attempting to call set_weights when commit/reveal is enabled'),
    (7, 54): ErrorInfo('SubtensorModule', 'CommitRevealDisabled', 'Attemtping to commit/reveal weights when disabled.'),
    (7, 55): ErrorInfo('SubtensorModule', 'LiquidAlphaDisabled', 'Attempting to set alpha high/low while disabled'),
    (7, 56): ErrorInfo('SubtensorModule', 'AlphaHighTooLow', 'Alpha high is too low: alpha_high > 0.8'),
    (7, 57): ErrorInfo('SubtensorModule', 'AlphaLowOutOfRange', 'Alpha low is out of range: alpha_low > 0 && alpha_low < 0.8'),
    (7, 58): ErrorInfo('SubtensorModule', 'ColdKeyAlreadyAssociated', 'The coldkey has already been swapped'),
    (7, 59): ErrorInfo('SubtensorModule', 'NotEnoughBalanceToPaySwapColdKey', 'The coldkey balance is not enough to pay for the swap'),
    (7, 60): ErrorInfo('SubtensorModule', 'InvalidChild', 'Attempting to set an invalid child for a hotkey on a network.'),
    (7, 61): ErrorInfo('SubtensorModule', 'DuplicateChild', 'Duplicate child when setting children.'),
    (7, 62): ErrorInfo('SubtensorModule', 'ProportionOverflow', 'Proportion overflow when setting children.'),
    (7, 63): ErrorInfo('SubtensorModule', 'TooManyChildren', 'Too many children MAX 5.'),
    (7, 64): ErrorInfo('SubtensorModule', 'TxRateLimitExceeded', 'Default transaction rate limit exceeded.'),
    (7, 65): ErrorInfo('SubtensorModule', 'ColdkeySwapAnnouncementNotFound', 'Coldkey swap announcement not found'),
    (7, 66): ErrorInfo('SubtensorModule', 'ColdkeySwapTooEarly', 'Coldkey swap too early.'),
    (7, 67): ErrorInfo('SubtensorModule', 'ColdkeySwapReannouncedTooEarly', 'Coldkey swap reannounced too early.'),
    (7, 68): ErrorInfo('SubtensorModule', 'AnnouncedColdkeyHashDoesNotMatch', 'The announced coldkey hash does not match the new coldkey hash.'),
    (7, 69): ErrorInfo('SubtensorModule', 'ColdkeySwapAlreadyDisputed', 'Coldkey swap already disputed'),
    (7, 70): ErrorInfo('SubtensorModule', 'NewColdKeyIsHotkey', 'New coldkey is hotkey'),
    (7, 71): ErrorInfo('SubtensorModule', 'InvalidChildkeyTake', 'Childkey take is invalid.'),
    (7, 72): ErrorInfo('SubtensorModule', 'TxChildkeyTakeRateLimitExceeded', 'Childkey take rate limit exceeded.'),
    (7, 73): ErrorInfo('SubtensorModule', 'InvalidIdentity', 'Invalid identity.'),
    (7, 74): ErrorInfo('SubtensorModule', 'MechanismDoesNotExist', 'Subnet mechanism does not exist.'),
    (7, 75): ErrorInfo('SubtensorModule', 'StakeUnavailable', 'Trying to unstake or re-lock the locked amount.'),
    (7, 76): ErrorInfo('SubtensorModule', 'SubnetNotExists', 'Trying to perform action on non-existent subnet.'),
    (7, 77): ErrorInfo('SubtensorModule', 'TooManyUnrevealedCommits', 'Maximum commit limit reached'),
    (7, 78): ErrorInfo('SubtensorModule', 'ExpiredWeightCommit', 'Attempted to reveal weights that are expired.'),
    (7, 79): ErrorInfo('SubtensorModule', 'RevealTooEarly', 'Attempted to reveal weights too early.'),
    (7, 80): ErrorInfo('SubtensorModule', 'InputLengthsUnequal', 'Attempted to batch reveal weights with mismatched vector input lenghts.'),
    (7, 81): ErrorInfo('SubtensorModule', 'CommittingWeightsTooFast', 'A transactor exceeded the rate limit for setting weights.'),
    (7, 82): ErrorInfo('SubtensorModule', 'AmountTooLow', 'Stake amount is too low.'),
    (7, 83): ErrorInfo('SubtensorModule', 'InsufficientLiquidity', 'Not enough liquidity.'),
    (7, 84): ErrorInfo('SubtensorModule', 'SlippageTooHigh', 'Slippage is too high for the transaction.'),
    (7, 85): ErrorInfo('SubtensorModule', 'TransferDisallowed', 'Subnet disallows transfer.'),
    (7, 86): ErrorInfo('SubtensorModule', 'ActivityCutoffTooLow', 'Activity cutoff is being set too low.'),
    (7, 87): ErrorInfo('SubtensorModule', 'CallDisabled', 'Call is disabled'),
    (7, 88): ErrorInfo('SubtensorModule', 'FirstEmissionBlockNumberAlreadySet', 'FirstEmissionBlockNumber is already set.'),
    (7, 89): ErrorInfo('SubtensorModule', 'NeedWaitingMoreBlocksToStarCall', 'need wait for more blocks to accept the start call extrinsic.'),
    (7, 90): ErrorInfo('SubtensorModule', 'NotEnoughAlphaOutToRecycle', 'Not enough AlphaOut on the subnet to recycle'),
    (7, 91): ErrorInfo('SubtensorModule', 'CannotBurnOrRecycleOnRootSubnet', 'Cannot burn or recycle TAO from root subnet'),
    (7, 92): ErrorInfo('SubtensorModule', 'UnableToRecoverPublicKey', 'Public key cannot be recovered.'),
    (7, 93): ErrorInfo('SubtensorModule', 'InvalidRecoveredPublicKey', 'Recovered public key is invalid.'),
    (7, 94): ErrorInfo('SubtensorModule', 'SubtokenDisabled', 'SubToken disabled now'),
    (7, 95): ErrorInfo('SubtensorModule', 'HotKeySwapOnSubnetIntervalNotPassed', 'Too frequent hotkey swap on subnet'),
    (7, 96): ErrorInfo('SubtensorModule', 'KeepStakeBlockedByCollateral', '`keep_stake` hotkey swap refused because the old hotkey still has standing miner collateral. Stake would stay on the old key while the UID moves, stranding the bond. Swap with `keep_stake=false` so collateral migrates with the UID (lineage maps track the rename).'),
    (7, 97): ErrorInfo('SubtensorModule', 'SameNetuid', 'Invalid netuid duplication'),
    (7, 98): ErrorInfo('SubtensorModule', 'InsufficientTaoBalance', 'The caller does not have enough TAO balance for the operation.'),
    (7, 99): ErrorInfo('SubtensorModule', 'InvalidLeaseBeneficiary', 'Invalid lease beneficiary to register the leased network.'),
    (7, 100): ErrorInfo('SubtensorModule', 'LeaseCannotEndInThePast', 'Lease cannot end in the past.'),
    (7, 101): ErrorInfo('SubtensorModule', 'LeaseNetuidNotFound', "Couldn't find the lease netuid."),
    (7, 102): ErrorInfo('SubtensorModule', 'LeaseDoesNotExist', 'Lease does not exist.'),
    (7, 103): ErrorInfo('SubtensorModule', 'LeaseHasNoEndBlock', 'Lease has no end block.'),
    (7, 104): ErrorInfo('SubtensorModule', 'LeaseHasNotEnded', 'Lease has not ended.'),
    (7, 105): ErrorInfo('SubtensorModule', 'Overflow', 'An overflow occurred.'),
    (7, 106): ErrorInfo('SubtensorModule', 'BeneficiaryDoesNotOwnHotkey', 'Beneficiary does not own hotkey.'),
    (7, 107): ErrorInfo('SubtensorModule', 'ExpectedBeneficiaryOrigin', 'Expected beneficiary origin.'),
    (7, 108): ErrorInfo('SubtensorModule', 'AdminActionProhibitedDuringWeightsWindow', 'Admin operation is prohibited during the protected weights window'),
    (7, 109): ErrorInfo('SubtensorModule', 'SymbolDoesNotExist', 'Symbol does not exist.'),
    (7, 110): ErrorInfo('SubtensorModule', 'SymbolAlreadyInUse', 'Symbol already in use.'),
    (7, 111): ErrorInfo('SubtensorModule', 'IncorrectCommitRevealVersion', 'Incorrect commit-reveal version.'),
    (7, 112): ErrorInfo('SubtensorModule', 'InvalidRevealRound', 'Reveal round is older than the most recently stored DRAND round.'),
    (7, 113): ErrorInfo('SubtensorModule', 'RevealPeriodTooLarge', 'Reveal period is too large.'),
    (7, 114): ErrorInfo('SubtensorModule', 'RevealPeriodTooSmall', 'Reveal period is too small.'),
    (7, 115): ErrorInfo('SubtensorModule', 'InvalidValue', 'Generic error for out-of-range parameter value'),
    (7, 116): ErrorInfo('SubtensorModule', 'SubnetLimitReached', 'Subnet limit reached & there is no eligible subnet to prune'),
    (7, 117): ErrorInfo('SubtensorModule', 'CannotAffordLockCost', 'Insufficient funds to meet the subnet lock cost'),
    (7, 118): ErrorInfo('SubtensorModule', 'EvmKeyAssociateRateLimitExceeded', 'exceeded the rate limit for associating an EVM key.'),
    (7, 119): ErrorInfo('SubtensorModule', 'EvmKeyAssociationLimitExceeded', 'The EVM address already has the maximum number of associated UIDs on this subnet.'),
    (7, 120): ErrorInfo('SubtensorModule', 'SameAutoStakeHotkeyAlreadySet', 'Same auto stake hotkey already set'),
    (7, 121): ErrorInfo('SubtensorModule', 'UidMapCouldNotBeCleared', 'The UID map for the subnet could not be cleared'),
    (7, 122): ErrorInfo('SubtensorModule', 'TrimmingWouldExceedMaxImmunePercentage', 'Trimming would exceed the max immune neurons percentage'),
    (7, 123): ErrorInfo('SubtensorModule', 'ChildParentInconsistency', 'Violating the rules of Childkey-Parentkey consistency'),
    (7, 124): ErrorInfo('SubtensorModule', 'InvalidNumRootClaim', 'Invalid number of root claims'),
    (7, 125): ErrorInfo('SubtensorModule', 'InvalidRootClaimThreshold', 'Invalid value of root claim threshold'),
    (7, 126): ErrorInfo('SubtensorModule', 'InvalidSubnetNumber', 'Exceeded subnet limit number or zero.'),
    (7, 127): ErrorInfo('SubtensorModule', 'TooManyUIDsPerMechanism', 'The maximum allowed UIDs times mechanism count should not exceed 256.'),
    (7, 128): ErrorInfo('SubtensorModule', 'VotingPowerTrackingNotEnabled', 'Voting power tracking is not enabled for this subnet.'),
    (7, 129): ErrorInfo('SubtensorModule', 'InvalidVotingPowerEmaAlpha', 'Invalid voting power EMA alpha value (must be <= 10^18).'),
    (7, 130): ErrorInfo('SubtensorModule', 'Deprecated', 'Deprecated call.'),
    (7, 131): ErrorInfo('SubtensorModule', 'SubnetBuybackRateLimitExceeded', 'Subnet buyback exceeded the operation rate limit'),
    (7, 132): ErrorInfo('SubtensorModule', 'NetworkDissolveAlreadyQueued', 'Network already in dissolved queue'),
    (7, 133): ErrorInfo('SubtensorModule', 'AddStakeBurnRateLimitExceeded', '"Add stake and burn" exceeded the operation rate limit'),
    (7, 134): ErrorInfo('SubtensorModule', 'ColdkeySwapAnnounced', 'A coldkey swap has been announced for this account.'),
    (7, 135): ErrorInfo('SubtensorModule', 'ColdkeySwapDisputed', 'A coldkey swap for this account is under dispute.'),
    (7, 136): ErrorInfo('SubtensorModule', 'ColdkeySwapClearTooEarly', 'Coldkey swap clear too early.'),
    (7, 137): ErrorInfo('SubtensorModule', 'DisabledTemporarily', 'Disabled temporarily.'),
    (7, 138): ErrorInfo('SubtensorModule', 'RegistrationPriceLimitExceeded', 'Registration Price Limit Exceeded'),
    (7, 139): ErrorInfo('SubtensorModule', 'LockHotkeyMismatch', 'Lock hotkey mismatch: existing lock is for a different hotkey.'),
    (7, 140): ErrorInfo('SubtensorModule', 'InsufficientStakeForLock', 'Insufficient stake on subnet to cover the lock amount.'),
    (7, 141): ErrorInfo('SubtensorModule', 'NoExistingLock', 'No existing lock found for the given coldkey and subnet.'),
    (7, 142): ErrorInfo('SubtensorModule', 'ActiveLockExists', 'There is already an active lock for the given coldkey.'),
    (7, 143): ErrorInfo('SubtensorModule', 'CannotUseSystemAccount', 'A system account cannot be used in this operation'),
    (7, 144): ErrorInfo('SubtensorModule', 'UnlockAmountTooHigh', 'Trying to unlock more than locked'),
    (7, 145): ErrorInfo('SubtensorModule', 'WaitingForDissolvedSubnetCleanup', 'Waiting for dissolved subnet cleanup.'),
    (7, 146): ErrorInfo('SubtensorModule', 'TempoOutOfBounds', 'The supplied tempo is outside the allowed range.'),
    (7, 147): ErrorInfo('SubtensorModule', 'ActivityCutoffFactorMilliOutOfBounds', 'The supplied activity-cutoff factor is outside the allowed range.'),
    (7, 148): ErrorInfo('SubtensorModule', 'EpochTriggerAlreadyPending', 'An epoch trigger is already pending for this subnet; wait for it to fire before triggering again.'),
    (7, 149): ErrorInfo('SubtensorModule', 'AutoEpochAlreadyImminent', 'The next automatic epoch is already imminent; a manual trigger would have no effect.'),
    (7, 150): ErrorInfo('SubtensorModule', 'DynamicTempoBlockedByCommitReveal', '`trigger_epoch` is blocked because commit-reveal is enabled for this subnet: an out-of-band epoch would desync the CRv3 reveal window from the wall-clock Drand schedule and silently drop committed weights.'),
    (7, 151): ErrorInfo('SubtensorModule', 'AccountRejectsLockedAlpha', 'The destination coldkey rejects incoming locked alpha.'),
    (7, 152): ErrorInfo('SubtensorModule', 'LockIdOverFlow', 'The coldkey has already registered too many subnets'),
    (7, 153): ErrorInfo('SubtensorModule', 'StartCallNotReady', 'Need to wait more blocks to do the start call.'),
    (7, 154): ErrorInfo('SubtensorModule', 'InsufficientAlphaBalance', 'The caller does not have enough Alpha stake for the operation.'),
    (7, 155): ErrorInfo('SubtensorModule', 'ColdkeyCollateralIncomplete', "Coldkey swap could not fully migrate miner collateral: the old coldkey's [`ColdkeyMinerCollateral`] aggregate remained non-zero after migrating every indexed collateral hotkey. Failing closed avoids under-locking the destination unstake guard."),
    (7, 156): ErrorInfo('SubtensorModule', 'ColdkeyCollateralPositionsFull', 'This coldkey already has the maximum number of distinct hotkeys with miner collateral on the subnet ([`crate::MAX_COLDKEY_COLLATERAL_HOTKEYS`]).'),
    (7, 157): ErrorInfo('SubtensorModule', 'TooManyRootClaimHotkeys', 'The coldkey has too many staking hotkeys for a single manual root claim.'),
    (7, 158): ErrorInfo('SubtensorModule', 'NoChallengeToAnswer', "No registration is currently waiting on this subnet's owner, or the window in which the owner could have answered one has already closed."),
    (7, 159): ErrorInfo('SubtensorModule', 'SubnetChallengeInProgress', "A registration is already waiting on this subnet's owner to decide. At most one challenge stands against a given subnet, so this registration is refused rather than queued behind it. Retry once the window closes or the owner answers."),
    (7, 160): ErrorInfo('SubtensorModule', 'NoQueuedRegistration', 'This coldkey holds no queued network registration under the given lock id. Either it was already served or cancelled, or the lock belongs to somebody else.'),
    (11, 0): ErrorInfo('Utility', 'TooManyCalls', 'Too many calls batched.'),
    (11, 1): ErrorInfo('Utility', 'InvalidDerivedAccount', 'Bad input data for derived account ID'),
    (12, 0): ErrorInfo('Sudo', 'RequireSudo', 'Sender must be the Sudo account.'),
    (13, 0): ErrorInfo('Multisig', 'MinimumThreshold', 'Threshold must be 2 or greater.'),
    (13, 1): ErrorInfo('Multisig', 'AlreadyApproved', 'Call is already approved by this signatory.'),
    (13, 2): ErrorInfo('Multisig', 'NoApprovalsNeeded', "Call doesn't need any (more) approvals."),
    (13, 3): ErrorInfo('Multisig', 'TooFewSignatories', 'There are too few signatories in the list.'),
    (13, 4): ErrorInfo('Multisig', 'TooManySignatories', 'There are too many signatories in the list.'),
    (13, 5): ErrorInfo('Multisig', 'SignatoriesOutOfOrder', 'The signatories were provided out of order; they should be ordered.'),
    (13, 6): ErrorInfo('Multisig', 'SenderInSignatories', "The sender was contained in the other signatories; it shouldn't be."),
    (13, 7): ErrorInfo('Multisig', 'NotFound', 'Multisig operation not found in storage.'),
    (13, 8): ErrorInfo('Multisig', 'NotOwner', 'Only the account that originally created the multisig is able to cancel it or update its deposits.'),
    (13, 9): ErrorInfo('Multisig', 'NoTimepoint', 'No timepoint was given, yet the multisig operation is already underway.'),
    (13, 10): ErrorInfo('Multisig', 'WrongTimepoint', 'A different timepoint was given to the multisig operation that is underway.'),
    (13, 11): ErrorInfo('Multisig', 'UnexpectedTimepoint', 'A timepoint was given, yet no multisig operation is underway.'),
    (13, 12): ErrorInfo('Multisig', 'MaxWeightTooLow', 'The maximum weight information provided was too low.'),
    (13, 13): ErrorInfo('Multisig', 'AlreadyStored', 'The data to be stored is already stored.'),
    (14, 0): ErrorInfo('Preimage', 'TooBig', 'Preimage is too large to store on-chain.'),
    (14, 1): ErrorInfo('Preimage', 'AlreadyNoted', 'Preimage has already been noted on-chain.'),
    (14, 2): ErrorInfo('Preimage', 'NotAuthorized', 'The user is not authorized to perform this action.'),
    (14, 3): ErrorInfo('Preimage', 'NotNoted', 'The preimage cannot be removed since it has not yet been noted.'),
    (14, 4): ErrorInfo('Preimage', 'Requested', 'A preimage may not be removed when there are outstanding requests.'),
    (14, 5): ErrorInfo('Preimage', 'NotRequested', 'The preimage request cannot be removed since no outstanding requests exist.'),
    (14, 6): ErrorInfo('Preimage', 'TooMany', 'More than `MAX_HASH_UPGRADE_BULK_COUNT` hashes were requested to be upgraded at once.'),
    (14, 7): ErrorInfo('Preimage', 'TooFew', 'Too few hashes were requested to be upgraded (i.e. zero).'),
    (15, 0): ErrorInfo('Scheduler', 'FailedToSchedule', 'Failed to schedule a call'),
    (15, 1): ErrorInfo('Scheduler', 'NotFound', 'Cannot find the scheduled call.'),
    (15, 2): ErrorInfo('Scheduler', 'TargetBlockNumberInPast', 'Given target block number is in the past.'),
    (15, 3): ErrorInfo('Scheduler', 'RescheduleNoChange', 'Reschedule failed because it does not change scheduled time.'),
    (15, 4): ErrorInfo('Scheduler', 'Named', 'Attempt to use a non-named function on a named task.'),
    (16, 0): ErrorInfo('Proxy', 'TooMany', 'There are too many proxies registered or too many announcements pending.'),
    (16, 1): ErrorInfo('Proxy', 'NotFound', 'Proxy registration not found.'),
    (16, 2): ErrorInfo('Proxy', 'NotProxy', 'Sender is not a proxy of the account to be proxied.'),
    (16, 3): ErrorInfo('Proxy', 'Unproxyable', "A call which is incompatible with the proxy type's filter was attempted."),
    (16, 4): ErrorInfo('Proxy', 'Duplicate', 'Account is already a proxy.'),
    (16, 5): ErrorInfo('Proxy', 'NoPermission', 'Call may not be made by proxy because it may escalate its privileges.'),
    (16, 6): ErrorInfo('Proxy', 'Unannounced', 'Announcement, if made at all, was made too recently.'),
    (16, 7): ErrorInfo('Proxy', 'NoSelfProxy', 'Cannot add self as proxy.'),
    (16, 8): ErrorInfo('Proxy', 'AnnouncementDepositInvariantViolated', 'Invariant violated: deposit recomputation returned None after updating announcements.'),
    (16, 9): ErrorInfo('Proxy', 'InvalidDerivedAccountId', 'Failed to derive a valid account id from the provided entropy.'),
    (18, 0): ErrorInfo('Commitments', 'TooManyFieldsInCommitmentInfo', 'Account passed too many additional fields to their commitment'),
    (18, 1): ErrorInfo('Commitments', 'AccountNotAllowedCommit', 'Account is not allowed to make commitments to the chain'),
    (18, 2): ErrorInfo('Commitments', 'SpaceLimitExceeded', 'Space Limit Exceeded for the current interval'),
    (18, 3): ErrorInfo('Commitments', 'UnexpectedUnreserveLeftover', 'Indicates that unreserve returned a leftover, which is unexpected.'),
    (19, 0): ErrorInfo('AdminUtils', 'SubnetDoesNotExist', 'The subnet does not exist, check the netuid parameter'),
    (19, 1): ErrorInfo('AdminUtils', 'MaxValidatorsLargerThanMaxUIds', 'The maximum number of subnet validators must be less than the maximum number of allowed UIDs in the subnet.'),
    (19, 2): ErrorInfo('AdminUtils', 'MaxAllowedUIdsLessThanCurrentUIds', 'The maximum number of subnet validators must be more than the current number of UIDs already in the subnet.'),
    (19, 3): ErrorInfo('AdminUtils', 'BondsMovingAverageMaxReached', 'The maximum value for bonds moving average is reached'),
    (19, 4): ErrorInfo('AdminUtils', 'NegativeSigmoidSteepness', 'Only root can set negative sigmoid steepness values'),
    (19, 5): ErrorInfo('AdminUtils', 'ValueNotInBounds', 'Value not in allowed bounds.'),
    (19, 6): ErrorInfo('AdminUtils', 'MinAllowedUidsGreaterThanCurrentUids', 'The minimum allowed UIDs must be less than the current number of UIDs in the subnet.'),
    (19, 7): ErrorInfo('AdminUtils', 'MinAllowedUidsGreaterThanMaxAllowedUids', 'The minimum allowed UIDs must be less than the maximum allowed UIDs.'),
    (19, 8): ErrorInfo('AdminUtils', 'MaxAllowedUidsLessThanMinAllowedUids', 'The maximum allowed UIDs must be greater than the minimum allowed UIDs.'),
    (19, 9): ErrorInfo('AdminUtils', 'MaxAllowedUidsGreaterThanDefaultMaxAllowedUids', 'The maximum allowed UIDs must be less than the default maximum allowed UIDs.'),
    (19, 10): ErrorInfo('AdminUtils', 'InvalidValue', 'Bad parameter value'),
    (19, 11): ErrorInfo('AdminUtils', 'NotPermittedOnRootSubnet', 'Operation is not permitted on the root network.'),
    (19, 12): ErrorInfo('AdminUtils', 'POWRegistrationDisabled', 'POW Registration has been deprecated'),
    (19, 13): ErrorInfo('AdminUtils', 'Deprecated', 'Call is deprecated'),
    (19, 14): ErrorInfo('AdminUtils', 'CollateralLockShareTooHigh', 'The collateral lock share exceeds the settable maximum (95% of the registration price).'),
    (19, 15): ErrorInfo('AdminUtils', 'CollateralDrainRatioOutOfBounds', 'The collateral drain ratio must be positive and at most the settable maximum.'),
    (20, 0): ErrorInfo('SafeMode', 'Entered', 'The safe-mode is (already or still) entered.'),
    (20, 1): ErrorInfo('SafeMode', 'Exited', 'The safe-mode is (already or still) exited.'),
    (20, 2): ErrorInfo('SafeMode', 'NotConfigured', 'This functionality of the pallet is disabled by the configuration.'),
    (20, 3): ErrorInfo('SafeMode', 'NoDeposit', 'There is no balance reserved.'),
    (20, 4): ErrorInfo('SafeMode', 'AlreadyDeposited', 'The account already has a deposit reserved and can therefore not enter or extend again.'),
    (20, 5): ErrorInfo('SafeMode', 'CannotReleaseYet', 'This deposit cannot be released yet.'),
    (20, 6): ErrorInfo('SafeMode', 'CurrencyError', 'An error from the underlying `Currency`.'),
    (21, 0): ErrorInfo('Ethereum', 'InvalidSignature', 'Signature is invalid.'),
    (21, 1): ErrorInfo('Ethereum', 'PreLogExists', 'Pre-log is present, therefore transact is not allowed.'),
    (22, 0): ErrorInfo('EVM', 'BalanceLow', 'Not enough balance to perform action'),
    (22, 1): ErrorInfo('EVM', 'FeeOverflow', 'Calculating total fee overflowed'),
    (22, 2): ErrorInfo('EVM', 'PaymentOverflow', 'Calculating total payment overflowed'),
    (22, 3): ErrorInfo('EVM', 'WithdrawFailed', 'Withdraw fee failed'),
    (22, 4): ErrorInfo('EVM', 'GasPriceTooLow', 'Gas price is too low.'),
    (22, 5): ErrorInfo('EVM', 'InvalidNonce', 'Nonce is invalid'),
    (22, 6): ErrorInfo('EVM', 'GasLimitTooLow', 'Gas limit is too low.'),
    (22, 7): ErrorInfo('EVM', 'GasLimitTooHigh', 'Gas limit is too high.'),
    (22, 8): ErrorInfo('EVM', 'InvalidChainId', 'The chain id is invalid.'),
    (22, 9): ErrorInfo('EVM', 'InvalidSignature', 'the signature is invalid.'),
    (22, 10): ErrorInfo('EVM', 'Reentrancy', 'EVM reentrancy'),
    (22, 11): ErrorInfo('EVM', 'TransactionMustComeFromEOA', 'EIP-3607,'),
    (22, 12): ErrorInfo('EVM', 'Undefined', 'Undefined error.'),
    (22, 13): ErrorInfo('EVM', 'NotAllowed', 'Origin is not allowed to perform the operation.'),
    (22, 14): ErrorInfo('EVM', 'CreateOriginNotAllowed', 'Address not allowed to deploy contracts either via CREATE or CALL(CREATE).'),
    (26, 0): ErrorInfo('Drand', 'NoneValue', 'The value retrieved was `None` as no value was previously set.'),
    (26, 1): ErrorInfo('Drand', 'StorageOverflow', 'There was an attempt to increment the value in storage over `u32::MAX`.'),
    (26, 2): ErrorInfo('Drand', 'DrandConnectionFailure', 'failed to connect to the'),
    (26, 3): ErrorInfo('Drand', 'UnverifiedPulse', 'the pulse is invalid'),
    (26, 4): ErrorInfo('Drand', 'InvalidRoundNumber', 'the round number did not increment'),
    (26, 5): ErrorInfo('Drand', 'PulseVerificationError', 'the pulse could not be verified'),
    (27, 0): ErrorInfo('Crowdloan', 'DepositTooLow', 'The crowdloan initial deposit is too low.'),
    (27, 1): ErrorInfo('Crowdloan', 'CapTooLow', 'The crowdloan cap is too low.'),
    (27, 2): ErrorInfo('Crowdloan', 'MinimumContributionTooLow', 'The minimum contribution is too low.'),
    (27, 3): ErrorInfo('Crowdloan', 'CannotEndInPast', 'The crowdloan cannot end in the past.'),
    (27, 4): ErrorInfo('Crowdloan', 'BlockDurationTooShort', 'The crowdloan block duration is too short.'),
    (27, 5): ErrorInfo('Crowdloan', 'BlockDurationTooLong', 'The block duration is too long.'),
    (27, 6): ErrorInfo('Crowdloan', 'InsufficientBalance', 'The account does not have enough balance to pay for the initial deposit/contribution.'),
    (27, 7): ErrorInfo('Crowdloan', 'Overflow', 'An overflow occurred.'),
    (27, 8): ErrorInfo('Crowdloan', 'InvalidCrowdloanId', 'The crowdloan id is invalid.'),
    (27, 9): ErrorInfo('Crowdloan', 'CapRaised', 'The crowdloan cap has been fully raised.'),
    (27, 10): ErrorInfo('Crowdloan', 'ContributionPeriodEnded', 'The contribution period has ended.'),
    (27, 11): ErrorInfo('Crowdloan', 'ContributionTooLow', 'The contribution is too low.'),
    (27, 12): ErrorInfo('Crowdloan', 'InvalidOrigin', 'The origin of this call is invalid.'),
    (27, 13): ErrorInfo('Crowdloan', 'AlreadyFinalized', 'The crowdloan has already been finalized.'),
    (27, 14): ErrorInfo('Crowdloan', 'AlreadyFinalizing', 'A crowdloan finalization is already in progress.'),
    (27, 15): ErrorInfo('Crowdloan', 'ContributionPeriodNotEnded', 'The crowdloan contribution period has not ended yet.'),
    (27, 16): ErrorInfo('Crowdloan', 'NoContribution', 'The contributor has no contribution for this crowdloan.'),
    (27, 17): ErrorInfo('Crowdloan', 'CapNotRaised', 'The crowdloan cap has not been raised.'),
    (27, 18): ErrorInfo('Crowdloan', 'Underflow', 'An underflow occurred.'),
    (27, 19): ErrorInfo('Crowdloan', 'CallUnavailable', 'Call to dispatch was not found in the preimage storage.'),
    (27, 20): ErrorInfo('Crowdloan', 'NotReadyToDissolve', 'The crowdloan is not ready to be dissolved, it still has contributions.'),
    (27, 21): ErrorInfo('Crowdloan', 'DepositCannotBeWithdrawn', 'The deposit cannot be withdrawn from the crowdloan.'),
    (27, 22): ErrorInfo('Crowdloan', 'MaxContributorsReached', 'The maximum number of contributors has been reached.'),
    (27, 23): ErrorInfo('Crowdloan', 'InvalidFinalizationConfig', 'Exactly one of call or target address must be provided.'),
    (27, 24): ErrorInfo('Crowdloan', 'MaxContributionReached', 'The contributor has already reached the maximum contribution.'),
    (27, 25): ErrorInfo('Crowdloan', 'MaximumContributionTooLow', 'The maximum contribution is too low.'),
    (27, 26): ErrorInfo('Crowdloan', 'MinimumContributionTooHigh', 'The minimum contribution is too high.'),
    (28, 0): ErrorInfo('Swap', 'FeeRateTooHigh', 'The fee rate is too high'),
    (28, 1): ErrorInfo('Swap', 'InsufficientInputAmount', 'The provided amount is insufficient for the swap.'),
    (28, 2): ErrorInfo('Swap', 'InsufficientLiquidity', 'The provided liquidity is insufficient for the operation.'),
    (28, 3): ErrorInfo('Swap', 'PriceLimitExceeded', 'The operation would exceed the price limit.'),
    (28, 4): ErrorInfo('Swap', 'InsufficientBalance', 'The caller does not have enough balance for the operation.'),
    (28, 5): ErrorInfo('Swap', 'InvalidTickRange', 'The provided tick range is invalid.'),
    (28, 6): ErrorInfo('Swap', 'InvalidLiquidityValue', 'Provided liquidity parameter is invalid (likely too small)'),
    (28, 7): ErrorInfo('Swap', 'ReservesTooLow', 'Reserves too low for operation.'),
    (28, 8): ErrorInfo('Swap', 'MechanismDoesNotExist', 'The subnet does not exist.'),
    (28, 9): ErrorInfo('Swap', 'SubtokenDisabled', 'The subnet does not have subtoken enabled'),
    (28, 10): ErrorInfo('Swap', 'ReservesOutOfBalance', 'Swap reserves are too imbalanced'),
    (28, 11): ErrorInfo('Swap', 'SwapInputTooLarge', 'Swap input is too large relative to input-side liquidity'),
    (28, 12): ErrorInfo('Swap', 'Deprecated', 'The extrinsic is deprecated'),
    (29, 0): ErrorInfo('Contracts', 'InvalidSchedule', 'Invalid schedule supplied, e.g. with zero weight of a basic operation.'),
    (29, 1): ErrorInfo('Contracts', 'InvalidCallFlags', 'Invalid combination of flags supplied to `seal_call` or `seal_delegate_call`.'),
    (29, 2): ErrorInfo('Contracts', 'OutOfGas', 'The executed contract exhausted its gas limit.'),
    (29, 3): ErrorInfo('Contracts', 'OutputBufferTooSmall', 'The output buffer supplied to a contract API call was too small.'),
    (29, 4): ErrorInfo('Contracts', 'TransferFailed', "Performing the requested transfer failed. Probably because there isn't enough free balance in the sender's account."),
    (29, 5): ErrorInfo('Contracts', 'MaxCallDepthReached', 'Performing a call was denied because the calling depth reached the limit of what is specified in the schedule.'),
    (29, 6): ErrorInfo('Contracts', 'ContractNotFound', 'No contract was found at the specified address.'),
    (29, 7): ErrorInfo('Contracts', 'CodeTooLarge', 'The code supplied to `instantiate_with_code` exceeds the limit specified in the current schedule.'),
    (29, 8): ErrorInfo('Contracts', 'CodeNotFound', 'No code could be found at the supplied code hash.'),
    (29, 9): ErrorInfo('Contracts', 'CodeInfoNotFound', 'No code info could be found at the supplied code hash.'),
    (29, 10): ErrorInfo('Contracts', 'OutOfBounds', 'A buffer outside of sandbox memory was passed to a contract API function.'),
    (29, 11): ErrorInfo('Contracts', 'DecodingFailed', 'Input passed to a contract API function failed to decode as expected type.'),
    (29, 12): ErrorInfo('Contracts', 'ContractTrapped', 'Contract trapped during execution.'),
    (29, 13): ErrorInfo('Contracts', 'ValueTooLarge', 'The size defined in `T::MaxValueSize` was exceeded.'),
    (29, 14): ErrorInfo('Contracts', 'TerminatedWhileReentrant', 'Termination of a contract is not allowed while the contract is already on the call stack. Can be triggered by `seal_terminate`.'),
    (29, 15): ErrorInfo('Contracts', 'InputForwarded', '`seal_call` forwarded this contracts input. It therefore is no longer available.'),
    (29, 16): ErrorInfo('Contracts', 'RandomSubjectTooLong', 'The subject passed to `seal_random` exceeds the limit.'),
    (29, 17): ErrorInfo('Contracts', 'TooManyTopics', 'The amount of topics passed to `seal_deposit_events` exceeds the limit.'),
    (29, 18): ErrorInfo('Contracts', 'NoChainExtension', "The chain does not provide a chain extension. Calling the chain extension results in this error. Note that this usually  shouldn't happen as deploying such contracts is rejected."),
    (29, 19): ErrorInfo('Contracts', 'XCMDecodeFailed', 'Failed to decode the XCM program.'),
    (29, 20): ErrorInfo('Contracts', 'DuplicateContract', 'A contract with the same AccountId already exists.'),
    (29, 21): ErrorInfo('Contracts', 'TerminatedInConstructor', 'A contract self destructed in its constructor.  This can be triggered by a call to `seal_terminate`.'),
    (29, 22): ErrorInfo('Contracts', 'ReentranceDenied', 'A call tried to invoke a contract that is flagged as non-reentrant. The only other cause is that a call from a contract into the runtime tried to call back into `pallet-contracts`. This would make the whole pallet reentrant with regard to contract code execution which is not supported.'),
    (29, 23): ErrorInfo('Contracts', 'StateChangeDenied', 'A contract attempted to invoke a state modifying API while being in read-only mode.'),
    (29, 24): ErrorInfo('Contracts', 'StorageDepositNotEnoughFunds', "Origin doesn't have enough balance to pay the required storage deposits."),
    (29, 25): ErrorInfo('Contracts', 'StorageDepositLimitExhausted', 'More storage was created than allowed by the storage deposit limit.'),
    (29, 26): ErrorInfo('Contracts', 'CodeInUse', 'Code removal was denied because the code is still in use by at least one contract.'),
    (29, 27): ErrorInfo('Contracts', 'ContractReverted', 'The contract ran to completion but decided to revert its storage changes. Please note that this error is only returned from extrinsics. When called directly or via RPC an `Ok` will be returned. In this case the caller needs to inspect the flags to determine whether a reversion has taken place.'),
    (29, 28): ErrorInfo('Contracts', 'CodeRejected', "The contract's code was found to be invalid during validation.  The most likely cause of this is that an API was used which is not supported by the node. This happens if an older node is used with a new version of ink!. Try updating your node to the newest available version.  A more detailed error can be found on the node console if debug messages are enabled by supplying `-lruntime::contracts=debug`."),
    (29, 29): ErrorInfo('Contracts', 'Indeterministic', 'An indeterministic code was used in a context where this is not permitted.'),
    (29, 30): ErrorInfo('Contracts', 'MigrationInProgress', 'A pending migration needs to complete before the extrinsic can be called.'),
    (29, 31): ErrorInfo('Contracts', 'NoMigrationPerformed', 'Migrate dispatch call was attempted but no migration was performed.'),
    (29, 32): ErrorInfo('Contracts', 'MaxDelegateDependenciesReached', 'The contract has reached its maximum number of delegate dependencies.'),
    (29, 33): ErrorInfo('Contracts', 'DelegateDependencyNotFound', "The dependency was not found in the contract's delegate dependencies."),
    (29, 34): ErrorInfo('Contracts', 'DelegateDependencyAlreadyExists', 'The contract already depends on the given delegate dependency.'),
    (29, 35): ErrorInfo('Contracts', 'CannotAddSelfAsDelegateDependency', 'Can not add a delegate dependency to the code hash of the contract itself.'),
    (29, 36): ErrorInfo('Contracts', 'OutOfTransientStorage', 'Can not add more data to transient storage.'),
    (30, 0): ErrorInfo('MevShield', 'BadEncKeyLen', 'The announced ML‑KEM encapsulation key length is invalid.'),
    (30, 1): ErrorInfo('MevShield', 'Unreachable', 'Unreachable.'),
    (30, 2): ErrorInfo('MevShield', 'TooManyPendingExtrinsics', 'Too many pending extrinsics in storage.'),
    (30, 3): ErrorInfo('MevShield', 'WeightExceedsAbsoluteMax', 'Weight exceeds the absolute maximum (half of total block weight).'),
    (32, 0): ErrorInfo('LimitOrders', 'InvalidSignature', 'The provided signature does not match the order payload and signer.'),
    (32, 1): ErrorInfo('LimitOrders', 'OrderAlreadyProcessed', 'The order has already been Fulfilled or Cancelled.'),
    (32, 2): ErrorInfo('LimitOrders', 'OrderCancelled', 'Order has been cancelled'),
    (32, 3): ErrorInfo('LimitOrders', 'OrderExpired', "The order's expiry timestamp is in the past."),
    (32, 4): ErrorInfo('LimitOrders', 'PriceConditionNotMet', "The current market price does not satisfy the order's limit price."),
    (32, 5): ErrorInfo('LimitOrders', 'Unauthorized', 'Caller is not the order signer (required for cancellation).'),
    (32, 6): ErrorInfo('LimitOrders', 'SwapReturnedZero', 'The pool swap returned zero output for a non-zero input.'),
    (32, 7): ErrorInfo('LimitOrders', 'RootNetUidNotAllowed', 'Root netuid (0) is not allowed for limit orders.'),
    (32, 8): ErrorInfo('LimitOrders', 'OrderNetUidMismatch', 'An order in the batch targets a different netuid than the batch netuid parameter.'),
    (32, 9): ErrorInfo('LimitOrders', 'LimitOrdersDisabled', 'Limit orders are disabled'),
    (32, 10): ErrorInfo('LimitOrders', 'RelayerMissMatch', 'Relayer not the same as specified in the order'),
    (32, 11): ErrorInfo('LimitOrders', 'PartialFillsNotEnabled', 'Partial fills not enabled for this order'),
    (32, 12): ErrorInfo('LimitOrders', 'IncorrectPartialFillAmount', 'Incorrect partial fill amount provided'),
    (32, 13): ErrorInfo('LimitOrders', 'RelayerRequiredForPartialFill', 'A relayer must be set on the order when using partial fills'),
    (32, 14): ErrorInfo('LimitOrders', 'ChainIdMismatch', "The order's chain_id does not match the current chain."),
    (32, 15): ErrorInfo('LimitOrders', 'PalletHotkeyNotRegistered', 'The pallet hotkey has not been registered to the pallet account. Call on_runtime_upgrade or wait for genesis to complete registration before enabling the pallet.'),
    (32, 16): ErrorInfo('LimitOrders', 'ArithmeticOverflow', 'A TAO -> alpha conversion overflowed the fixed-point range.'),
    (32, 17): ErrorInfo('LimitOrders', 'DuplicateOrderInBatch', 'The same order appears more than once in a single batch.'),
    (32, 18): ErrorInfo('LimitOrders', 'ZeroShareInBatch', "An order's pro-rata share in the batch rounded down to zero. The whole batch is rejected so the order's input is never consumed without delivering any output (conservation), and the order stays retryable in a differently-composed batch."),
}
