"""Generated from runtime metadata by codegen. DO NOT EDIT BY HAND.

Regenerate with: python -m codegen <ws-endpoint>
Spec version: 441

Storage item descriptors: unpack into substrate.query/query_map. Each carries its VALUE's type identity (value_type_ident) so normalization can key on the runtime's own type names without a node round-trip.
"""
from typing import NamedTuple


class Item(NamedTuple):
    """A (container, name) pair; unpack into query/constant calls."""

    container: str
    name: str
    value_type_ident: str = ''

    def __iter__(self):
        # Unpacking feeds (module, storage_function) signatures; value_type_ident
        # is metadata for normalization, reached by attribute only.
        return iter((self.container, self.name))


class System:
    Account = Item('System', 'Account', 'AccountInfo')
    ExtrinsicCount = Item('System', 'ExtrinsicCount', 'u32')
    InherentsApplied = Item('System', 'InherentsApplied', 'bool')
    BlockWeight = Item('System', 'BlockWeight', 'PerDispatchClass')
    AllExtrinsicsLen = Item('System', 'AllExtrinsicsLen', 'u32')
    BlockHash = Item('System', 'BlockHash', 'H256')
    ExtrinsicData = Item('System', 'ExtrinsicData', 'Vec<u8>')
    Number = Item('System', 'Number', 'u32')
    ParentHash = Item('System', 'ParentHash', 'H256')
    Digest = Item('System', 'Digest', 'Digest')
    Events = Item('System', 'Events', 'Vec<EventRecord>')
    EventCount = Item('System', 'EventCount', 'u32')
    EventTopics = Item('System', 'EventTopics', 'Vec<(u32, u32)>')
    LastRuntimeUpgrade = Item('System', 'LastRuntimeUpgrade', 'LastRuntimeUpgradeInfo')
    UpgradedToU32RefCount = Item('System', 'UpgradedToU32RefCount', 'bool')
    UpgradedToTripleRefCount = Item('System', 'UpgradedToTripleRefCount', 'bool')
    ExecutionPhase = Item('System', 'ExecutionPhase', 'Phase')
    AuthorizedUpgrade = Item('System', 'AuthorizedUpgrade', 'CodeUpgradeAuthorization')
    ExtrinsicWeightReclaimed = Item('System', 'ExtrinsicWeightReclaimed', 'Weight')

class RandomnessCollectiveFlip:
    RandomMaterial = Item('RandomnessCollectiveFlip', 'RandomMaterial', 'BoundedVec')

class Timestamp:
    Now = Item('Timestamp', 'Now', 'u64')
    DidUpdate = Item('Timestamp', 'DidUpdate', 'bool')

class Aura:
    Authorities = Item('Aura', 'Authorities', 'BoundedVec')
    CurrentSlot = Item('Aura', 'CurrentSlot', 'Slot')

class Grandpa:
    State = Item('Grandpa', 'State', 'StoredState')
    PendingChange = Item('Grandpa', 'PendingChange', 'StoredPendingChange')
    NextForced = Item('Grandpa', 'NextForced', 'u32')
    Stalled = Item('Grandpa', 'Stalled', '(u32, u32)')
    CurrentSetId = Item('Grandpa', 'CurrentSetId', 'u64')
    SetIdSession = Item('Grandpa', 'SetIdSession', 'u32')
    Authorities = Item('Grandpa', 'Authorities', 'WeakBoundedVec')

class Balances:
    TotalIssuance = Item('Balances', 'TotalIssuance', 'TaoBalance')
    InactiveIssuance = Item('Balances', 'InactiveIssuance', 'TaoBalance')
    Account = Item('Balances', 'Account', 'AccountData')
    Locks = Item('Balances', 'Locks', 'WeakBoundedVec')
    Reserves = Item('Balances', 'Reserves', 'BoundedVec')
    Holds = Item('Balances', 'Holds', 'BoundedVec')
    Freezes = Item('Balances', 'Freezes', 'BoundedVec')

class TransactionPayment:
    NextFeeMultiplier = Item('TransactionPayment', 'NextFeeMultiplier', 'FixedU128')
    StorageVersion = Item('TransactionPayment', 'StorageVersion', 'Releases')

class SubtensorModule:
    MinActivityCutoff = Item('SubtensorModule', 'MinActivityCutoff', 'u16')
    AdminFreezeWindow = Item('SubtensorModule', 'AdminFreezeWindow', 'u16')
    OwnerHyperparamRateLimit = Item('SubtensorModule', 'OwnerHyperparamRateLimit', 'u16')
    DissolveNetworkScheduleDuration = Item('SubtensorModule', 'DissolveNetworkScheduleDuration', 'u32')
    LastHotkeySwapOnNetuid = Item('SubtensorModule', 'LastHotkeySwapOnNetuid', 'u64')
    HotkeySuccessor = Item('SubtensorModule', 'HotkeySuccessor', 'AccountId32')
    HotkeyRoot = Item('SubtensorModule', 'HotkeyRoot', 'AccountId32')
    ColdkeySuccessor = Item('SubtensorModule', 'ColdkeySuccessor', 'AccountId32')
    ColdkeyRoot = Item('SubtensorModule', 'ColdkeyRoot', 'AccountId32')
    NextStakeJobId = Item('SubtensorModule', 'NextStakeJobId', 'u64')
    TaoWeight = Item('SubtensorModule', 'TaoWeight', 'u64')
    CKBurn = Item('SubtensorModule', 'CKBurn', 'u64')
    MaxDelegateTake = Item('SubtensorModule', 'MaxDelegateTake', 'PerU16')
    MinDelegateTake = Item('SubtensorModule', 'MinDelegateTake', 'PerU16')
    MaxChildkeyTake = Item('SubtensorModule', 'MaxChildkeyTake', 'PerU16')
    MinChildkeyTake = Item('SubtensorModule', 'MinChildkeyTake', 'PerU16')
    MinChildkeyTakePerSubnet = Item('SubtensorModule', 'MinChildkeyTakePerSubnet', 'PerU16')
    Owner = Item('SubtensorModule', 'Owner', 'AccountId32')
    AccountFlags = Item('SubtensorModule', 'AccountFlags', 'u128')
    Delegates = Item('SubtensorModule', 'Delegates', 'PerU16')
    ChildkeyTake = Item('SubtensorModule', 'ChildkeyTake', 'PerU16')
    PendingChildKeys = Item('SubtensorModule', 'PendingChildKeys', '(Vec<(u64, AccountId32)>, u64)')
    ChildKeys = Item('SubtensorModule', 'ChildKeys', 'Vec<(u64, AccountId32)>')
    ParentKeys = Item('SubtensorModule', 'ParentKeys', 'Vec<(u64, AccountId32)>')
    AlphaDividendsPerSubnet = Item('SubtensorModule', 'AlphaDividendsPerSubnet', 'AlphaBalance')
    RootAlphaDividendsPerSubnet = Item('SubtensorModule', 'RootAlphaDividendsPerSubnet', 'AlphaBalance')
    BlockEmission = Item('SubtensorModule', 'BlockEmission', 'u64')
    LastHotkeyEmissionOnNetuid = Item('SubtensorModule', 'LastHotkeyEmissionOnNetuid', 'AlphaBalance')
    SubnetLimit = Item('SubtensorModule', 'SubnetLimit', 'u16')
    TotalIssuance = Item('SubtensorModule', 'TotalIssuance', 'TaoBalance')
    TotalStake = Item('SubtensorModule', 'TotalStake', 'TaoBalance')
    SubnetMovingAlpha = Item('SubtensorModule', 'SubnetMovingAlpha', 'FixedI128')
    SubnetMovingPrice = Item('SubtensorModule', 'SubnetMovingPrice', 'FixedI128')
    RootProp = Item('SubtensorModule', 'RootProp', 'FixedU128')
    SubnetVolume = Item('SubtensorModule', 'SubnetVolume', 'u128')
    SubnetTAO = Item('SubtensorModule', 'SubnetTAO', 'TaoBalance')
    SubnetAlphaInEmission = Item('SubtensorModule', 'SubnetAlphaInEmission', 'AlphaBalance')
    SubnetEmissionEnabled = Item('SubtensorModule', 'SubnetEmissionEnabled', 'bool')
    SubnetAlphaOutEmission = Item('SubtensorModule', 'SubnetAlphaOutEmission', 'AlphaBalance')
    SubnetTaoInEmission = Item('SubtensorModule', 'SubnetTaoInEmission', 'TaoBalance')
    SubnetExcessTao = Item('SubtensorModule', 'SubnetExcessTao', 'TaoBalance')
    SubnetRootSellTao = Item('SubtensorModule', 'SubnetRootSellTao', 'TaoBalance')
    SubnetAlphaIn = Item('SubtensorModule', 'SubnetAlphaIn', 'AlphaBalance')
    SubnetAlphaOut = Item('SubtensorModule', 'SubnetAlphaOut', 'AlphaBalance')
    SubnetProtocolAlpha = Item('SubtensorModule', 'SubnetProtocolAlpha', 'AlphaBalance')
    StakingHotkeys = Item('SubtensorModule', 'StakingHotkeys', 'Vec<AccountId32>')
    OwnedHotkeys = Item('SubtensorModule', 'OwnedHotkeys', 'Vec<AccountId32>')
    AutoStakeDestination = Item('SubtensorModule', 'AutoStakeDestination', 'AccountId32')
    AutoStakeDestinationColdkeys = Item('SubtensorModule', 'AutoStakeDestinationColdkeys', 'Vec<AccountId32>')
    ColdkeySwapAnnouncementDelay = Item('SubtensorModule', 'ColdkeySwapAnnouncementDelay', 'u32')
    ColdkeySwapReannouncementDelay = Item('SubtensorModule', 'ColdkeySwapReannouncementDelay', 'u32')
    ColdkeySwapAnnouncements = Item('SubtensorModule', 'ColdkeySwapAnnouncements', '(u32, H256)')
    ColdkeySwapDisputes = Item('SubtensorModule', 'ColdkeySwapDisputes', 'u32')
    TotalHotkeyAlpha = Item('SubtensorModule', 'TotalHotkeyAlpha', 'AlphaBalance')
    TotalHotkeyAlphaLastEpoch = Item('SubtensorModule', 'TotalHotkeyAlphaLastEpoch', 'AlphaBalance')
    TotalHotkeyShares = Item('SubtensorModule', 'TotalHotkeyShares', 'FixedU128')
    Alpha = Item('SubtensorModule', 'Alpha', 'FixedU128')
    TotalHotkeySharesV2 = Item('SubtensorModule', 'TotalHotkeySharesV2', 'SafeFloat')
    AlphaV2 = Item('SubtensorModule', 'AlphaV2', 'SafeFloat')
    Lock = Item('SubtensorModule', 'Lock', 'LockState')
    LockingColdkeys = Item('SubtensorModule', 'LockingColdkeys', '()')
    HotkeyLock = Item('SubtensorModule', 'HotkeyLock', 'LockState')
    DecayingHotkeyLock = Item('SubtensorModule', 'DecayingHotkeyLock', 'LockState')
    OwnerLock = Item('SubtensorModule', 'OwnerLock', 'LockState')
    DecayingOwnerLock = Item('SubtensorModule', 'DecayingOwnerLock', 'LockState')
    DecayingLock = Item('SubtensorModule', 'DecayingLock', 'bool')
    OwnerCutAutoLockEnabled = Item('SubtensorModule', 'OwnerCutAutoLockEnabled', 'bool')
    MaturityRate = Item('SubtensorModule', 'MaturityRate', 'u64')
    UnlockRate = Item('SubtensorModule', 'UnlockRate', 'u64')
    AlphaMapLastKey = Item('SubtensorModule', 'AlphaMapLastKey', 'Option<Vec<u8>>')
    AlphaV2MapLastKey = Item('SubtensorModule', 'AlphaV2MapLastKey', 'Option<Vec<u8>>')
    TokenSymbol = Item('SubtensorModule', 'TokenSymbol', 'Vec<u8>')
    SubnetTaoFlow = Item('SubtensorModule', 'SubnetTaoFlow', 'i64')
    SubnetEmaTaoFlow = Item('SubtensorModule', 'SubnetEmaTaoFlow', '(u64, FixedI128)')
    NetTaoFlowEnabled = Item('SubtensorModule', 'NetTaoFlowEnabled', 'bool')
    SubnetProtocolFlow = Item('SubtensorModule', 'SubnetProtocolFlow', 'i64')
    SubnetEmaProtocolFlow = Item('SubtensorModule', 'SubnetEmaProtocolFlow', '(u64, FixedI128)')
    TaoFlowCutoff = Item('SubtensorModule', 'TaoFlowCutoff', 'FixedI128')
    FlowNormExponent = Item('SubtensorModule', 'FlowNormExponent', 'FixedU128')
    EmissionBarQuantile = Item('SubtensorModule', 'EmissionBarQuantile', 'FixedU128')
    EmissionGateExponent = Item('SubtensorModule', 'EmissionGateExponent', 'FixedU128')
    EmissionGateBar = Item('SubtensorModule', 'EmissionGateBar', 'FixedU128')
    FlowEmaSmoothingFactor = Item('SubtensorModule', 'FlowEmaSmoothingFactor', 'u64')
    UsedWork = Item('SubtensorModule', 'UsedWork', 'u64')
    MaxRegistrationsPerBlock = Item('SubtensorModule', 'MaxRegistrationsPerBlock', 'u16')
    TotalNetworks = Item('SubtensorModule', 'TotalNetworks', 'u16')
    NetworkImmunityPeriod = Item('SubtensorModule', 'NetworkImmunityPeriod', 'u64')
    StartCallDelay = Item('SubtensorModule', 'StartCallDelay', 'u64')
    NetworkMinLockCost = Item('SubtensorModule', 'NetworkMinLockCost', 'TaoBalance')
    NetworkLastLockCost = Item('SubtensorModule', 'NetworkLastLockCost', 'TaoBalance')
    NetworkLockReductionInterval = Item('SubtensorModule', 'NetworkLockReductionInterval', 'u64')
    SubnetOwnerCut = Item('SubtensorModule', 'SubnetOwnerCut', 'u16')
    OwnerCutEnabled = Item('SubtensorModule', 'OwnerCutEnabled', 'bool')
    NetworkRateLimit = Item('SubtensorModule', 'NetworkRateLimit', 'u64')
    NominatorMinRequiredStake = Item('SubtensorModule', 'NominatorMinRequiredStake', 'u64')
    WeightsVersionKeyRateLimit = Item('SubtensorModule', 'WeightsVersionKeyRateLimit', 'u64')
    LastRateLimitedBlock = Item('SubtensorModule', 'LastRateLimitedBlock', 'u64')
    TransferToggle = Item('SubtensorModule', 'TransferToggle', 'bool')
    SubnetLocked = Item('SubtensorModule', 'SubnetLocked', 'TaoBalance')
    LargestLocked = Item('SubtensorModule', 'LargestLocked', 'u64')
    Tempo = Item('SubtensorModule', 'Tempo', 'u16')
    LastEpochBlock = Item('SubtensorModule', 'LastEpochBlock', 'u64')
    PendingEpochAt = Item('SubtensorModule', 'PendingEpochAt', 'u64')
    SubnetEpochIndex = Item('SubtensorModule', 'SubnetEpochIndex', 'u64')
    ActivityCutoffFactorMilli = Item('SubtensorModule', 'ActivityCutoffFactorMilli', 'u32')
    FirstEmissionBlockNumber = Item('SubtensorModule', 'FirstEmissionBlockNumber', 'u64')
    SubnetMechanism = Item('SubtensorModule', 'SubnetMechanism', 'u16')
    SubnetworkN = Item('SubtensorModule', 'SubnetworkN', 'u16')
    NetworksAdded = Item('SubtensorModule', 'NetworksAdded', 'bool')
    IsNetworkMember = Item('SubtensorModule', 'IsNetworkMember', 'bool')
    NetworkRegistrationAllowed = Item('SubtensorModule', 'NetworkRegistrationAllowed', 'bool')
    NetworkPowRegistrationAllowed = Item('SubtensorModule', 'NetworkPowRegistrationAllowed', 'bool')
    NetworkRegisteredAt = Item('SubtensorModule', 'NetworkRegisteredAt', 'u64')
    NetworkImmuneUntil = Item('SubtensorModule', 'NetworkImmuneUntil', 'u64')
    SubnetRefusalWindow = Item('SubtensorModule', 'SubnetRefusalWindow', 'RefusalWindow')
    RegisteredSubnetCounter = Item('SubtensorModule', 'RegisteredSubnetCounter', 'u64')
    PendingServerEmission = Item('SubtensorModule', 'PendingServerEmission', 'AlphaBalance')
    PendingValidatorEmission = Item('SubtensorModule', 'PendingValidatorEmission', 'AlphaBalance')
    PendingRootAlphaDivs = Item('SubtensorModule', 'PendingRootAlphaDivs', 'AlphaBalance')
    PendingOwnerCut = Item('SubtensorModule', 'PendingOwnerCut', 'AlphaBalance')
    MinerBurned = Item('SubtensorModule', 'MinerBurned', 'FixedU128')
    BlocksSinceLastStep = Item('SubtensorModule', 'BlocksSinceLastStep', 'u64')
    LastMechansimStepBlock = Item('SubtensorModule', 'LastMechansimStepBlock', 'u64')
    SubnetOwner = Item('SubtensorModule', 'SubnetOwner', 'AccountId32')
    SubnetOwnerHotkey = Item('SubtensorModule', 'SubnetOwnerHotkey', 'AccountId32')
    RecycleOrBurn = Item('SubtensorModule', 'RecycleOrBurn', 'RecycleOrBurnEnum')
    ServingRateLimit = Item('SubtensorModule', 'ServingRateLimit', 'u64')
    Rho = Item('SubtensorModule', 'Rho', 'u16')
    AlphaSigmoidSteepness = Item('SubtensorModule', 'AlphaSigmoidSteepness', 'i16')
    Kappa = Item('SubtensorModule', 'Kappa', 'u16')
    RegistrationsThisInterval = Item('SubtensorModule', 'RegistrationsThisInterval', 'u16')
    POWRegistrationsThisInterval = Item('SubtensorModule', 'POWRegistrationsThisInterval', 'u16')
    BurnRegistrationsThisInterval = Item('SubtensorModule', 'BurnRegistrationsThisInterval', 'u16')
    MinAllowedUids = Item('SubtensorModule', 'MinAllowedUids', 'u16')
    MaxAllowedUids = Item('SubtensorModule', 'MaxAllowedUids', 'u16')
    ImmunityPeriod = Item('SubtensorModule', 'ImmunityPeriod', 'u16')
    ActivityCutoff = Item('SubtensorModule', 'ActivityCutoff', 'u16')
    MaxWeightsLimit = Item('SubtensorModule', 'MaxWeightsLimit', 'u16')
    WeightsVersionKey = Item('SubtensorModule', 'WeightsVersionKey', 'u64')
    MinAllowedWeights = Item('SubtensorModule', 'MinAllowedWeights', 'u16')
    MaxAllowedValidators = Item('SubtensorModule', 'MaxAllowedValidators', 'u16')
    AdjustmentInterval = Item('SubtensorModule', 'AdjustmentInterval', 'u16')
    BondsMovingAverage = Item('SubtensorModule', 'BondsMovingAverage', 'u64')
    BondsPenalty = Item('SubtensorModule', 'BondsPenalty', 'u16')
    BondsResetOn = Item('SubtensorModule', 'BondsResetOn', 'bool')
    WeightsSetRateLimit = Item('SubtensorModule', 'WeightsSetRateLimit', 'u64')
    ValidatorPruneLen = Item('SubtensorModule', 'ValidatorPruneLen', 'u64')
    ScalingLawPower = Item('SubtensorModule', 'ScalingLawPower', 'u16')
    TargetRegistrationsPerInterval = Item('SubtensorModule', 'TargetRegistrationsPerInterval', 'u16')
    AdjustmentAlpha = Item('SubtensorModule', 'AdjustmentAlpha', 'u64')
    CommitRevealWeightsEnabled = Item('SubtensorModule', 'CommitRevealWeightsEnabled', 'bool')
    Burn = Item('SubtensorModule', 'Burn', 'TaoBalance')
    Difficulty = Item('SubtensorModule', 'Difficulty', 'u64')
    MinBurn = Item('SubtensorModule', 'MinBurn', 'TaoBalance')
    MaxBurn = Item('SubtensorModule', 'MaxBurn', 'TaoBalance')
    MinDifficulty = Item('SubtensorModule', 'MinDifficulty', 'u64')
    MaxDifficulty = Item('SubtensorModule', 'MaxDifficulty', 'u64')
    LastAdjustmentBlock = Item('SubtensorModule', 'LastAdjustmentBlock', 'u64')
    RegistrationsThisBlock = Item('SubtensorModule', 'RegistrationsThisBlock', 'u16')
    EMAPriceHalvingBlocks = Item('SubtensorModule', 'EMAPriceHalvingBlocks', 'u64')
    RAORecycledForRegistration = Item('SubtensorModule', 'RAORecycledForRegistration', 'TaoBalance')
    MaxEpochsPerBlock = Item('SubtensorModule', 'MaxEpochsPerBlock', 'u8')
    TxRateLimit = Item('SubtensorModule', 'TxRateLimit', 'u64')
    TxDelegateTakeRateLimit = Item('SubtensorModule', 'TxDelegateTakeRateLimit', 'u64')
    TxChildkeyTakeRateLimit = Item('SubtensorModule', 'TxChildkeyTakeRateLimit', 'u64')
    LiquidAlphaOn = Item('SubtensorModule', 'LiquidAlphaOn', 'bool')
    Yuma3On = Item('SubtensorModule', 'Yuma3On', 'bool')
    AlphaValues = Item('SubtensorModule', 'AlphaValues', '(u16, u16)')
    SubtokenEnabled = Item('SubtensorModule', 'SubtokenEnabled', 'bool')
    DissolveCleanupQueue = Item('SubtensorModule', 'DissolveCleanupQueue', 'Vec<NetUid>')
    CurrentDissolveCleanupStatus = Item('SubtensorModule', 'CurrentDissolveCleanupStatus', 'DissolveCleanupStatus')
    NetworkRegistrationQueue = Item('SubtensorModule', 'NetworkRegistrationQueue', 'Vec<NetworkRegistrationInfo>')
    NetworkRegistrationLockId = Item('SubtensorModule', 'NetworkRegistrationLockId', 'u32')
    VotingPower = Item('SubtensorModule', 'VotingPower', 'u64')
    VotingPowerTrackingEnabled = Item('SubtensorModule', 'VotingPowerTrackingEnabled', 'bool')
    VotingPowerDisableAtBlock = Item('SubtensorModule', 'VotingPowerDisableAtBlock', 'u64')
    VotingPowerEmaAlpha = Item('SubtensorModule', 'VotingPowerEmaAlpha', 'u64')
    ImmuneOwnerUidsLimit = Item('SubtensorModule', 'ImmuneOwnerUidsLimit', 'u16')
    StakeWeight = Item('SubtensorModule', 'StakeWeight', 'Vec<u16>')
    Uids = Item('SubtensorModule', 'Uids', 'u16')
    Keys = Item('SubtensorModule', 'Keys', 'AccountId32')
    LoadedEmission = Item('SubtensorModule', 'LoadedEmission', 'Vec<(AccountId32, u64, u64)>')
    Active = Item('SubtensorModule', 'Active', 'Vec<bool>')
    Consensus = Item('SubtensorModule', 'Consensus', 'Vec<PerU16>')
    Incentive = Item('SubtensorModule', 'Incentive', 'Vec<PerU16>')
    Dividends = Item('SubtensorModule', 'Dividends', 'Vec<PerU16>')
    Emission = Item('SubtensorModule', 'Emission', 'Vec<AlphaBalance>')
    LastUpdate = Item('SubtensorModule', 'LastUpdate', 'Vec<u64>')
    ValidatorTrust = Item('SubtensorModule', 'ValidatorTrust', 'Vec<PerU16>')
    ValidatorPermit = Item('SubtensorModule', 'ValidatorPermit', 'Vec<bool>')
    Weights = Item('SubtensorModule', 'Weights', 'Vec<(u16, u16)>')
    Bonds = Item('SubtensorModule', 'Bonds', 'Vec<(u16, u16)>')
    BlockAtRegistration = Item('SubtensorModule', 'BlockAtRegistration', 'u64')
    Axons = Item('SubtensorModule', 'Axons', 'AxonInfo')
    NeuronCertificates = Item('SubtensorModule', 'NeuronCertificates', 'NeuronCertificate')
    Prometheus = Item('SubtensorModule', 'Prometheus', 'PrometheusInfo')
    IdentitiesV2 = Item('SubtensorModule', 'IdentitiesV2', 'ChainIdentityV2')
    SubnetIdentitiesV3 = Item('SubtensorModule', 'SubnetIdentitiesV3', 'SubnetIdentityV3')
    TransactionKeyLastBlock = Item('SubtensorModule', 'TransactionKeyLastBlock', 'u64')
    LastTxBlock = Item('SubtensorModule', 'LastTxBlock', 'u64')
    LastTxBlockChildKeyTake = Item('SubtensorModule', 'LastTxBlockChildKeyTake', 'u64')
    LastTxBlockDelegateTake = Item('SubtensorModule', 'LastTxBlockDelegateTake', 'u64')
    StakeThreshold = Item('SubtensorModule', 'StakeThreshold', 'u64')
    WeightCommits = Item('SubtensorModule', 'WeightCommits', 'Vec<(H256, u64, u64, u64)>')
    TimelockedWeightCommits = Item('SubtensorModule', 'TimelockedWeightCommits', 'Vec<(AccountId32, u64, BoundedVec, u64)>')
    CRV3WeightCommits = Item('SubtensorModule', 'CRV3WeightCommits', 'Vec<(AccountId32, BoundedVec, u64)>')
    CRV3WeightCommitsV2 = Item('SubtensorModule', 'CRV3WeightCommitsV2', 'Vec<(AccountId32, u64, BoundedVec, u64)>')
    RevealPeriodEpochs = Item('SubtensorModule', 'RevealPeriodEpochs', 'u64')
    LastColdkeyHotkeyStakeBlock = Item('SubtensorModule', 'LastColdkeyHotkeyStakeBlock', 'u64')
    RootClaimableThreshold = Item('SubtensorModule', 'RootClaimableThreshold', 'FixedI128')
    RootClaimable = Item('SubtensorModule', 'RootClaimable', 'BTreeMap')
    RootClaimed = Item('SubtensorModule', 'RootClaimed', 'u128')
    RootClaimType = Item('SubtensorModule', 'RootClaimType', 'RootClaimTypeEnum')
    StakingColdkeysByIndex = Item('SubtensorModule', 'StakingColdkeysByIndex', 'AccountId32')
    StakingColdkeys = Item('SubtensorModule', 'StakingColdkeys', 'u64')
    NumStakingColdkeys = Item('SubtensorModule', 'NumStakingColdkeys', 'u64')
    NumRootClaim = Item('SubtensorModule', 'NumRootClaim', 'u64')
    AssociatedEvmAddress = Item('SubtensorModule', 'AssociatedEvmAddress', '(H160, u64)')
    AssociatedUidsByEvmAddress = Item('SubtensorModule', 'AssociatedUidsByEvmAddress', 'BoundedVec')
    SubnetLeases = Item('SubtensorModule', 'SubnetLeases', 'SubnetLease')
    SubnetLeaseShares = Item('SubtensorModule', 'SubnetLeaseShares', 'FixedU128')
    SubnetUidToLeaseId = Item('SubtensorModule', 'SubnetUidToLeaseId', 'u32')
    NextSubnetLeaseId = Item('SubtensorModule', 'NextSubnetLeaseId', 'u32')
    AccumulatedLeaseDividends = Item('SubtensorModule', 'AccumulatedLeaseDividends', 'AlphaBalance')
    CommitRevealWeightsVersion = Item('SubtensorModule', 'CommitRevealWeightsVersion', 'u16')
    NetworkRegistrationStartBlock = Item('SubtensorModule', 'NetworkRegistrationStartBlock', 'u64')
    TaoInRefundDeploymentBlock = Item('SubtensorModule', 'TaoInRefundDeploymentBlock', 'u64')
    MinNonImmuneUids = Item('SubtensorModule', 'MinNonImmuneUids', 'u16')
    MaxMechanismCount = Item('SubtensorModule', 'MaxMechanismCount', 'MechId')
    MechanismCountCurrent = Item('SubtensorModule', 'MechanismCountCurrent', 'MechId')
    MechanismEmissionSplit = Item('SubtensorModule', 'MechanismEmissionSplit', 'Vec<u16>')
    BurnHalfLife = Item('SubtensorModule', 'BurnHalfLife', 'u16')
    BurnIncreaseMult = Item('SubtensorModule', 'BurnIncreaseMult', 'FixedU128')
    CollateralLockShare = Item('SubtensorModule', 'CollateralLockShare', 'u16')
    CollateralDrainRatio = Item('SubtensorModule', 'CollateralDrainRatio', 'FixedU128')
    MinerCollateral = Item('SubtensorModule', 'MinerCollateral', 'MinerCollateralState')
    ColdkeyMinerCollateral = Item('SubtensorModule', 'ColdkeyMinerCollateral', 'AlphaBalance')
    ColdkeyCollateralHotkeys = Item('SubtensorModule', 'ColdkeyCollateralHotkeys', 'BoundedVec')
    AutoParentDelegationEnabled = Item('SubtensorModule', 'AutoParentDelegationEnabled', 'bool')
    HasMigrationRun = Item('SubtensorModule', 'HasMigrationRun', 'bool')
    PendingChildKeyCooldown = Item('SubtensorModule', 'PendingChildKeyCooldown', 'u64')

class Sudo:
    Key = Item('Sudo', 'Key', 'AccountId32')

class Multisig:
    Multisigs = Item('Multisig', 'Multisigs', 'Multisig')

class Preimage:
    StatusFor = Item('Preimage', 'StatusFor', 'OldRequestStatus')
    RequestStatusFor = Item('Preimage', 'RequestStatusFor', 'RequestStatus')
    PreimageFor = Item('Preimage', 'PreimageFor', 'BoundedVec')

class Scheduler:
    IncompleteSince = Item('Scheduler', 'IncompleteSince', 'u32')
    Agenda = Item('Scheduler', 'Agenda', 'BoundedVec')
    Retries = Item('Scheduler', 'Retries', 'RetryConfig')
    Lookup = Item('Scheduler', 'Lookup', '(u32, u32)')

class Proxy:
    Proxies = Item('Proxy', 'Proxies', '(BoundedVec, TaoBalance)')
    Announcements = Item('Proxy', 'Announcements', '(BoundedVec, TaoBalance)')
    LastCallResult = Item('Proxy', 'LastCallResult', 'Result')
    RealPaysFee = Item('Proxy', 'RealPaysFee', '()')

class Commitments:
    TimelockedIndex = Item('Commitments', 'TimelockedIndex', 'BTreeSet')
    CommitmentOf = Item('Commitments', 'CommitmentOf', 'Registration')
    LastCommitment = Item('Commitments', 'LastCommitment', 'u32')
    LastBondsReset = Item('Commitments', 'LastBondsReset', 'u32')
    RevealedCommitments = Item('Commitments', 'RevealedCommitments', 'Vec<(Vec<u8>, u64)>')
    UsedSpaceOf = Item('Commitments', 'UsedSpaceOf', 'UsageTracker')
    MaxSpace = Item('Commitments', 'MaxSpace', 'u32')

class AdminUtils:
    PrecompileEnable = Item('AdminUtils', 'PrecompileEnable', 'bool')

class SafeMode:
    EnteredUntil = Item('SafeMode', 'EnteredUntil', 'u32')
    Deposits = Item('SafeMode', 'Deposits', 'TaoBalance')

class Ethereum:
    Pending = Item('Ethereum', 'Pending', '(TransactionV3, TransactionStatus, ReceiptV4)')
    CounterForPending = Item('Ethereum', 'CounterForPending', 'u32')
    CurrentBlock = Item('Ethereum', 'CurrentBlock', 'Block')
    CurrentReceipts = Item('Ethereum', 'CurrentReceipts', 'Vec<ReceiptV4>')
    CurrentTransactionStatuses = Item('Ethereum', 'CurrentTransactionStatuses', 'Vec<TransactionStatus>')
    BlockHash = Item('Ethereum', 'BlockHash', 'H256')

class EVM:
    AccountCodes = Item('EVM', 'AccountCodes', 'Vec<u8>')
    AccountCodesMetadata = Item('EVM', 'AccountCodesMetadata', 'CodeMetadata')
    AccountStorages = Item('EVM', 'AccountStorages', 'H256')
    WhitelistedCreators = Item('EVM', 'WhitelistedCreators', 'Vec<H160>')
    DisableWhitelistCheck = Item('EVM', 'DisableWhitelistCheck', 'bool')

class EVMChainId:
    ChainId = Item('EVMChainId', 'ChainId', 'u64')

class BaseFee:
    BaseFeePerGas = Item('BaseFee', 'BaseFeePerGas', 'U256')
    Elasticity = Item('BaseFee', 'Elasticity', 'Permill')

class Drand:
    BeaconConfig = Item('Drand', 'BeaconConfig', 'BeaconConfiguration')
    HasMigrationRun = Item('Drand', 'HasMigrationRun', 'bool')
    Pulses = Item('Drand', 'Pulses', 'Pulse')
    LastStoredRound = Item('Drand', 'LastStoredRound', 'u64')
    OldestStoredRound = Item('Drand', 'OldestStoredRound', 'u64')
    NextUnsignedAt = Item('Drand', 'NextUnsignedAt', 'u32')

class Crowdloan:
    Crowdloans = Item('Crowdloan', 'Crowdloans', 'CrowdloanInfo')
    NextCrowdloanId = Item('Crowdloan', 'NextCrowdloanId', 'u32')
    Contributions = Item('Crowdloan', 'Contributions', 'TaoBalance')
    MaxContributions = Item('Crowdloan', 'MaxContributions', 'TaoBalance')
    CurrentCrowdloanId = Item('Crowdloan', 'CurrentCrowdloanId', 'u32')
    HasMigrationRun = Item('Crowdloan', 'HasMigrationRun', 'bool')

class Swap:
    FeeRate = Item('Swap', 'FeeRate', 'u16')
    SwapBalancer = Item('Swap', 'SwapBalancer', 'Balancer')
    PalSwapInitialized = Item('Swap', 'PalSwapInitialized', 'bool')
    BalancerTaoReservoir = Item('Swap', 'BalancerTaoReservoir', 'TaoBalance')
    BalancerAlphaReservoir = Item('Swap', 'BalancerAlphaReservoir', 'AlphaBalance')
    HasMigrationRun = Item('Swap', 'HasMigrationRun', 'bool')
    ScrapReservoirAlpha = Item('Swap', 'ScrapReservoirAlpha', 'AlphaBalance')

class Contracts:
    PristineCode = Item('Contracts', 'PristineCode', 'BoundedVec')
    CodeInfoOf = Item('Contracts', 'CodeInfoOf', 'CodeInfo')
    Nonce = Item('Contracts', 'Nonce', 'u64')
    ContractInfoOf = Item('Contracts', 'ContractInfoOf', 'ContractInfo')
    DeletionQueue = Item('Contracts', 'DeletionQueue', 'BoundedVec')
    DeletionQueueCounter = Item('Contracts', 'DeletionQueueCounter', 'DeletionQueueManager')
    MigrationInProgress = Item('Contracts', 'MigrationInProgress', 'BoundedVec')

class MevShield:
    CurrentKey = Item('MevShield', 'CurrentKey', 'BoundedVec')
    PendingKey = Item('MevShield', 'PendingKey', 'BoundedVec')
    NextKey = Item('MevShield', 'NextKey', 'BoundedVec')
    AuthorKeys = Item('MevShield', 'AuthorKeys', 'BoundedVec')
    PendingKeyExpiresAt = Item('MevShield', 'PendingKeyExpiresAt', 'u32')
    NextKeyExpiresAt = Item('MevShield', 'NextKeyExpiresAt', 'u32')
    HasMigrationRun = Item('MevShield', 'HasMigrationRun', 'bool')
    MaxPendingExtrinsicsLimit = Item('MevShield', 'MaxPendingExtrinsicsLimit', 'u32')
    ExtrinsicLifetime = Item('MevShield', 'ExtrinsicLifetime', 'u32')
    OnInitializeWeight = Item('MevShield', 'OnInitializeWeight', 'u64')
    MaxExtrinsicWeight = Item('MevShield', 'MaxExtrinsicWeight', 'u64')
    PendingExtrinsics = Item('MevShield', 'PendingExtrinsics', 'PendingExtrinsic')
    CounterForPendingExtrinsics = Item('MevShield', 'CounterForPendingExtrinsics', 'u32')
    NextPendingExtrinsicIndex = Item('MevShield', 'NextPendingExtrinsicIndex', 'u32')

class AlphaAssets:
    TotalAlphaIssuance = Item('AlphaAssets', 'TotalAlphaIssuance', 'AlphaBalance')
    AlphaBurned = Item('AlphaAssets', 'AlphaBurned', 'AlphaBalance')
    AlphaRecycled = Item('AlphaAssets', 'AlphaRecycled', 'AlphaBalance')

class LimitOrders:
    Orders = Item('LimitOrders', 'Orders', 'OrderStatus')
    LimitOrdersEnabled = Item('LimitOrders', 'LimitOrdersEnabled', 'bool')
    HasMigrationRun = Item('LimitOrders', 'HasMigrationRun', 'bool')

